import { GoogleGenAI, Modality } from "@google/genai";
import type { GenerateContentResponse } from "@google/genai";

export const generateThumbnail = async (title: string, imageBase64: string, mimeType: string, aspectRatio: string): Promise<string> => {
    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

    const prompt = `
    Create a professional, scroll-stopping YouTube video thumbnail with a strict ${aspectRatio} aspect ratio.

    **Video Title:** "${title}"

    **Strict Requirement:**
    - The final output image MUST be ${aspectRatio}.
    - If the input image is not ${aspectRatio}, extend the background to fill the ${aspectRatio} frame.
    - Do not produce images in other aspect ratios.

    **Instructions:**
    1.  Use the provided headshot image as the central subject. The person in the image is the YouTuber.
    2.  Modify the YouTuber's facial expression to realistically match the tone and emotion of the video title (e.g., excitement, shock, curiosity, seriousness). Keep it realistic, not a caricature.
    3.  Design a visually stunning background that complements the video title. Use high-contrast, vibrant colors and cinematic depth of field (blurry background) to make the subject pop.
    4.  Add glowing highlights and dramatic lighting to the subject and key elements to create a dynamic and engaging look.
    5.  Incorporate the video title text onto the thumbnail. Use a bold, modern, and highly readable font. The text placement should be strategic, eye-catching, and not obscure the YouTuber's face.
    6.  The final image must look like it was made by a professional YouTube designer, fully optimized for a high click-through rate.
    `;

    const response: GenerateContentResponse = await ai.models.generateContent({
        model: 'gemini-2.5-flash-image',
        contents: {
            parts: [
                {
                    inlineData: {
                        data: imageBase64,
                        mimeType: mimeType,
                    },
                },
                {
                    text: prompt,
                },
            ],
        },
        config: {
            responseModalities: [Modality.IMAGE],
        },
    });

    const candidate = response.candidates?.[0];

    if (!candidate) {
        throw new Error("No candidates returned from the API.");
    }

    // Handle cases where the model refuses to generate content (e.g., safety filters)
    if (candidate.finishReason && candidate.finishReason !== 'STOP') {
        throw new Error(`Generation stopped due to: ${candidate.finishReason}`);
    }

    if (!candidate.content || !candidate.content.parts) {
        throw new Error("The model returned no content. It may have been blocked by safety settings.");
    }

    for (const part of candidate.content.parts) {
        if (part.inlineData) {
            return part.inlineData.data;
        }
    }

    throw new Error("No image was generated by the API.");
};